# Generated by Django 6.0.1 on 2026-01-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('page', models.CharField(default='/', max_length=500)),
                ('referrer', models.TextField(blank=True, default='')),
                ('user_agent', models.TextField(blank=True, default='')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('sent_contact', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
