# Generated by Django 6.0.1 on 2026-01-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sitevisitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=60)),
                ('summary', models.TextField()),
                ('changed_files', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('machine_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-deployed_at'],
            },
        ),
    ]
